### PR TITLE
feat: Add rotation to ios

### PR DESCRIPTION
**Pull request by juanmartin8a**
Add the rotation functionality to iOS. It rotates the image with the given rotation parameter from the InputImage metadata. I use it to rotate the image when the camera in flutter is locked to "portrait up".

### CODE REVIEW

**Comment by fbernaly** [comment]
I think this should be added to this file instead: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_commons/ios/Classes/MLKVisionImage%2BFlutterPlugin.m#L6-L18

**Comment by juanmartin8a** [comment]
> I think this should be added to this file instead: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_commons/ios/Classes/MLKVisionImage%2BFlutterPlugin.m#L6-L18

Done :)

**Review by fbernaly — APPROVED** [review]

**Comment by fbernaly** [comment]
This changes are breaking the example app. I will need to revert them. Please submit another PR and make sure our example app works correctly with all the APIs.

**Comment by juanmartin8a** [comment]
Sure. Should the rotation be determined using the device orientation directly on obj-c or using the rotation parameter that is sent in the metadata through the channel?

**Pull request merged**
