### PR TITLE
fix: Updated text recognition dependency

### PR DESCRIPTION
**Pull request by Mikkelet**
Update dependency to fix restraints bug from https://github.com/flutter-ml/google_ml_kit_flutter/issues/612

### CODE REVIEW

**Comment by fbernaly** [comment]
@Mikkelet: where did you find that latest dependencies? I am in the process of releasing a new version. Could you also update the podspecs for the other plugin as well.

**Comment by fbernaly** [comment]
Also, update your branch with the latest code we just merged.

**Comment by Mikkelet** [comment]
Yeah their website doc is lacking, had to go into their sample apps to get the right version:

https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts
https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile

I can see you've commented the dependency out of Document Scanner and FaceMeshDetection. I couldn't find any versions for these in the sample apps, so I assume they're only available for Android?

**Comment by fbernaly** [comment]
They are no available for iOS yet, only android.

**Comment by fbernaly** [comment]
Thanks for your contribution. I am merging this, and releasing on Monday.

**Review by fbernaly — APPROVED** [review]

**Comment by fbernaly** [comment]
@Mikkelet: I tried to run those with the example app and it is not able to find version 6.0.0, it finds 5.0.0. Did you test the changes with the example app? give it a try an update accordingly. Submit a new PR with the changes.

**Comment by Mikkelet** [comment]
ah no, sorry, I assumed that the versions used in the official sample apps would be correct, but I can see now that they are not. I also tried with going back to my initial commit where I only updated the version for text-recognition, 

but something weird is happening. When I update to 6.0.0, I can compile my flutter project, but *not* the example project. When I downgrade to 4.0.0, I can compile the example project, but *not* my personal project. Any clues to why that is?

**Comment by fbernaly** [comment]
Try 5.0.0 that works in the example. Send a PR with those changes.

**Pull request merged**
