### PR TITLE
fix: Support AGP 8

### LINKED ISSUE #509: Doesn't support AGP 8
Getting the error:

```FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_mlkit_commons'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

Pretty sure we just need to add a 

```
    if (project.android.hasProperty("namespace")) {
        namespace 'com.google_mlkit_commons'
    }
```

### PR DESCRIPTION
**Pull request by DanMossa**
Fixes #509

### CODE REVIEW

**Comment by fbernaly** [comment]
how do you reproduce the error this is fixing?

**Comment by DanMossa** [comment]
@fbernaly Set your gradle to version 8 and try building the app. It'll fail

**Comment by DanMossa** [comment]
@fbernaly I can do it within the next few days!

**Comment by fbernaly** [comment]
Thanks, let me know when you are done

**Comment by fbernaly** [comment]
@DanMossa : is this backwards compatible? can this work on old versions of gradle < 8?

**Comment by Zazo032** [comment]
> @DanMossa : is this backwards compatible? can this work on old versions of gradle < 8?

Yes, the added code checks if the project has set the namespace property (e.g. it's already using AGP 8) and in that case, it adds the namespace property

**Review by fbernaly — APPROVED** [review]

**Comment by fbernaly** [comment]
Thanks for your contribution @DanMossa !

**Pull request merged**
